version: "2"

volumes:
    sense-data:
    dashboard-data:
    iobrokerdata:

services:
  influxdb:
    restart: always
    image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    volumes:
      - 'sense-data:/var/lib/influxdb'
  dashboard:
    image: balenablocks/dashboard
    restart: always
    volumes:
      - 'dashboard-data:/data'
    ports:
      - '80'
  sensor:
    build: .
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.supervisor-api: '1'
    expose:
      - '7575'
    environment:
      RAW_VALUES: '0'
      COLLAPSE_FIELDS: '1'
  connector:
    image: balenablocks/connector
    restart: always
    labels:
      io.balena.features.balena-api: '1'
    privileged: true
    ports:
      - "8080"
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always
  iobroker:
    container_name: iobroker
    image: buanet/iobroker:v6.1.0-arm64v8
    hostname: iobroker
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - 'iobrokerdata:/opt/iobroker'
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    network_mode: host
